{
  "name": "Model",
  "compatibilityLevel": 1600,
  "model": {
    "culture": "fr-FR",
    "collation": "Latin1_General_100_BIN2_UTF8",
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "sourceQueryCulture": "en-US",
    "tables": [
      {
        "name": "CLIENT",
        "lineageTag": "7a39412a-7da5-4213-bbdc-53a74f1138eb",
        "columns": [
          {
            "name": "id_cli",
            "dataType": "string",
            "sourceColumn": "id_cli",
            "summarizeBy": "none",
            "lineageTag": "25942462-48e6-4ab8-bea1-6b0747c2d417",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "cli_c_p",
            "dataType": "string",
            "sourceColumn": "cli_c_p",
            "summarizeBy": "none",
            "lineageTag": "9e1c0542-203a-47bb-9ec6-ebb447bca7e7",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "nom_cplt",
            "dataType": "string",
            "sourceColumn": "nom_cplt",
            "summarizeBy": "none",
            "lineageTag": "f86fd6c6-0532-4fb8-b658-21bf9deea929",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "lib_cd_typ",
            "dataType": "string",
            "sourceColumn": "lib_cd_typ",
            "summarizeBy": "none",
            "lineageTag": "ba38358b-db4d-4f45-af2e-203a6e7bb61d",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "lib_gr",
            "dataType": "string",
            "sourceColumn": "lib_gr",
            "summarizeBy": "none",
            "lineageTag": "e9875b43-6c1a-43c7-a623-498fef3285b8",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "agc_topz",
            "dataType": "string",
            "sourceColumn": "agc_topz",
            "summarizeBy": "none",
            "lineageTag": "2d104fd1-0452-4395-b6fa-2d29fd25fff7",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "lib_ptf",
            "dataType": "string",
            "sourceColumn": "lib_ptf",
            "summarizeBy": "none",
            "lineageTag": "e40cf452-d8f5-4623-a36a-be435551a5e3",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "nom_cons",
            "dataType": "string",
            "sourceColumn": "nom_cons",
            "summarizeBy": "none",
            "lineageTag": "70d2daa0-37a1-4193-aa28-c21eba412d55",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "pay_res",
            "dataType": "string",
            "sourceColumn": "pay_res",
            "summarizeBy": "none",
            "lineageTag": "d7d444d8-f34c-45e0-8f3a-ab7fad230815",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "lib_pay_res",
            "dataType": "string",
            "sourceColumn": "lib_pay_res",
            "summarizeBy": "none",
            "lineageTag": "9ea72383-a3b8-4313-9027-68df1452053d",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "couleur_pays",
            "dataType": "string",
            "sourceColumn": "couleur_pays",
            "summarizeBy": "none",
            "lineageTag": "70fe51bb-64d1-4166-bbb0-1a98bec10b25",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "lib_cd_risque_pers",
            "dataType": "string",
            "sourceColumn": "lib_cd_risque_pers",
            "summarizeBy": "none",
            "lineageTag": "c99f3cba-fe1d-4f47-9038-1f924c55c8c9",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "cd_risque_pers",
            "dataType": "string",
            "sourceColumn": "cd_risque_pers",
            "summarizeBy": "none",
            "lineageTag": "b52ac399-7d52-44c3-91fb-a5f2e4d63c31",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "etat_acc",
            "dataType": "string",
            "sourceColumn": "etat_acc",
            "summarizeBy": "none",
            "lineageTag": "50b1c81f-616b-458c-89e6-28992f93189d",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "top_client_actif",
            "dataType": "string",
            "sourceColumn": "top_client_actif",
            "summarizeBy": "none",
            "lineageTag": "9fc1b459-4cb4-478a-95bb-308e38260f19",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "typ_enrol",
            "dataType": "string",
            "sourceColumn": "typ_enrol",
            "summarizeBy": "none",
            "lineageTag": "b95756ad-9f4e-4c4a-b070-ac53dbc6d963",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "gelule_global",
            "dataType": "int64",
            "sourceColumn": "gelule_global",
            "summarizeBy": "sum",
            "lineageTag": "10e87cfb-4b38-4f59-b891-29f737b7431d",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "nb_dev_enrol",
            "dataType": "int64",
            "sourceColumn": "nb_dev_enrol",
            "summarizeBy": "sum",
            "lineageTag": "3affc926-d8b2-457b-90f5-116076bf4bf8",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "age_cli",
            "dataType": "int64",
            "sourceColumn": "age_cli",
            "summarizeBy": "sum",
            "lineageTag": "937071e4-b87d-420c-8484-6b59404c11f8",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "dt_enrol",
            "dataType": "dateTime",
            "sourceColumn": "dt_enrol",
            "summarizeBy": "none",
            "lineageTag": "8e2c0c9e-92d4-4376-b8b2-ba8a48aac910",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "dt_der_cnx",
            "dataType": "dateTime",
            "sourceColumn": "dt_der_cnx",
            "summarizeBy": "none",
            "lineageTag": "cfda83c1-8df9-4248-b36c-7b35d9f22d1d",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "dt_fonc",
            "dataType": "dateTime",
            "sourceColumn": "dt_fonc",
            "summarizeBy": "none",
            "lineageTag": "deebf424-13a6-43c6-93b3-9c95c9ba0ac5",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "aum_tit",
            "dataType": "double",
            "sourceColumn": "aum_tit",
            "summarizeBy": "sum",
            "lineageTag": "de3fca10-2d6c-4ea8-b548-96845f68fccf",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "aum_cot",
            "dataType": "double",
            "sourceColumn": "aum_cot",
            "summarizeBy": "sum",
            "lineageTag": "b235152a-7f4e-4d19-a243-9d325d85728f",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "mnt_pat_epargne",
            "dataType": "double",
            "sourceColumn": "mnt_pat_epargne",
            "summarizeBy": "sum",
            "lineageTag": "a290347d-3576-44d1-a770-dd4860c0ca5d",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "mnt_rev_princ",
            "dataType": "double",
            "sourceColumn": "mnt_rev_princ",
            "summarizeBy": "sum",
            "lineageTag": "918a9663-f232-4f43-810e-0ba3dac8f5cd",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "CLIENT",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"E:\\\\louvre\\\\powerbi\\\\data\\\\CLIENT.csv\"),[Delimiter=\",\", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),",
                "    #\"Promoted\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    #\"Typed\" = Table.TransformColumnTypes(#\"Promoted\", {{\"id_cli\", type text}, {\"cli_c_p\", type text}, {\"nom_cplt\", type text}, {\"lib_cd_typ\", type text}, {\"lib_gr\", type text}, {\"agc_topz\", type text}, {\"lib_ptf\", type text}, {\"nom_cons\", type text}, {\"pay_res\", type text}, {\"lib_pay_res\", type text}, {\"couleur_pays\", type text}, {\"lib_cd_risque_pers\", type text}, {\"cd_risque_pers\", type text}, {\"etat_acc\", type text}, {\"top_client_actif\", type text}, {\"typ_enrol\", type text}, {\"gelule_global\", Int64.Type}, {\"nb_dev_enrol\", Int64.Type}, {\"age_cli\", Int64.Type}, {\"dt_enrol\", type date}, {\"dt_der_cnx\", type date}, {\"dt_fonc\", type date}, {\"aum_tit\", type number}, {\"aum_cot\", type number}, {\"mnt_pat_epargne\", type number}, {\"mnt_rev_princ\", type number}}, \"en-US\")",
                "in",
                "    #\"Typed\""
              ]
            }
          }
        ]
      },
      {
        "name": "TRANSACTION",
        "lineageTag": "bea09ce1-e075-4bf3-8899-8ec38654eaea",
        "columns": [
          {
            "name": "id_cli",
            "dataType": "string",
            "sourceColumn": "id_cli",
            "summarizeBy": "none",
            "lineageTag": "72673b66-e8ca-4f51-8d5f-843fd21bc8cf",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "num_cnt",
            "dataType": "string",
            "sourceColumn": "num_cnt",
            "summarizeBy": "none",
            "lineageTag": "df94ec35-baa7-4d16-98c8-11f45d52cc86",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "perimetre",
            "dataType": "string",
            "sourceColumn": "perimetre",
            "summarizeBy": "none",
            "lineageTag": "cb1ab048-3009-4199-a8f8-7b1b83c1184f",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "typ_evt_lv1",
            "dataType": "string",
            "sourceColumn": "typ_evt_lv1",
            "summarizeBy": "none",
            "lineageTag": "b7dff61f-244a-4849-b881-ac70d2a5a394",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "lib_evt_lv1",
            "dataType": "string",
            "sourceColumn": "lib_evt_lv1",
            "summarizeBy": "none",
            "lineageTag": "3480e0c7-ea1e-4157-991e-42275fb7ad66",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "sens",
            "dataType": "string",
            "sourceColumn": "sens",
            "summarizeBy": "none",
            "lineageTag": "5f54cc32-6a91-468a-bbdd-61c6f04a4818",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "mnt_evt",
            "dataType": "double",
            "sourceColumn": "mnt_evt",
            "summarizeBy": "sum",
            "lineageTag": "31308c29-0f17-4044-a8b8-3f720c20c0fc",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "devise_compte",
            "dataType": "string",
            "sourceColumn": "devise_compte",
            "summarizeBy": "none",
            "lineageTag": "b35e2b34-eeb9-4480-8da5-c02be9465d3b",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "mode_paiement",
            "dataType": "string",
            "sourceColumn": "mode_paiement",
            "summarizeBy": "none",
            "lineageTag": "79df99cf-11e5-433d-b3d9-9a2248ce5835",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "canal_ordre",
            "dataType": "string",
            "sourceColumn": "canal_ordre",
            "summarizeBy": "none",
            "lineageTag": "63135c26-da31-4294-87fa-3f0b07f1ddf5",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "ctrpty_pays",
            "dataType": "string",
            "sourceColumn": "ctrpty_pays",
            "summarizeBy": "none",
            "lineageTag": "895eae88-a724-45f0-a21e-37bee2916a4e",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "ctrpty_couleur_pays",
            "dataType": "string",
            "sourceColumn": "ctrpty_couleur_pays",
            "summarizeBy": "none",
            "lineageTag": "5c027923-2758-4925-b4fb-963ce3458cc3",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "ind_3ds",
            "dataType": "int64",
            "sourceColumn": "ind_3ds",
            "summarizeBy": "sum",
            "lineageTag": "d411df3e-c894-4bcb-ac6f-90e18b96acaf",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Transaction_Sensible",
            "dataType": "int64",
            "sourceColumn": "Transaction_Sensible",
            "summarizeBy": "sum",
            "lineageTag": "e67c4e5d-fefd-464d-9e63-50ada2d071d3",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "dt_realisation",
            "dataType": "dateTime",
            "sourceColumn": "dt_realisation",
            "summarizeBy": "none",
            "lineageTag": "9329dc0a-5659-4d05-8470-5968852d23db",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "TRANSACTION",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"E:\\\\louvre\\\\powerbi\\\\data\\\\TRANSACTION.csv\"),[Delimiter=\",\", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),",
                "    #\"Promoted\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    #\"Typed\" = Table.TransformColumnTypes(#\"Promoted\", {{\"id_cli\", type text}, {\"num_cnt\", type text}, {\"perimetre\", type text}, {\"typ_evt_lv1\", type text}, {\"lib_evt_lv1\", type text}, {\"sens\", type text}, {\"mnt_evt\", type number}, {\"devise_compte\", type text}, {\"mode_paiement\", type text}, {\"canal_ordre\", type text}, {\"ctrpty_pays\", type text}, {\"ctrpty_couleur_pays\", type text}, {\"ind_3ds\", Int64.Type}, {\"Transaction_Sensible\", Int64.Type}, {\"dt_realisation\", type date}}, \"en-US\")",
                "in",
                "    #\"Typed\""
              ]
            }
          }
        ]
      },
      {
        "name": "EPARGNE",
        "lineageTag": "bdf06269-ac42-4cec-b934-31ac19fe885d",
        "columns": [
          {
            "name": "id_cli",
            "dataType": "string",
            "sourceColumn": "id_cli",
            "summarizeBy": "none",
            "lineageTag": "859f6f7e-b78d-40b8-86dc-84a2280979ef",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "num_cnt",
            "dataType": "string",
            "sourceColumn": "num_cnt",
            "summarizeBy": "none",
            "lineageTag": "5264eb22-d1b8-463d-a344-52d9b525933f",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "perimetre",
            "dataType": "string",
            "sourceColumn": "perimetre",
            "summarizeBy": "none",
            "lineageTag": "0f52c238-1f7f-4c63-b79f-817efa9664f7",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "fam_pdt",
            "dataType": "string",
            "sourceColumn": "fam_pdt",
            "summarizeBy": "none",
            "lineageTag": "bd6aabfe-263c-4a92-ac12-65a429de26ab",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "lib_fds",
            "dataType": "string",
            "sourceColumn": "lib_fds",
            "summarizeBy": "none",
            "lineageTag": "d013a93e-b1cc-44c8-90c5-9510273c5d92",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "isin_fds",
            "dataType": "string",
            "sourceColumn": "isin_fds",
            "summarizeBy": "none",
            "lineageTag": "881e9513-0bcc-4193-a4e7-2b584172983a",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "lib_mod_gest",
            "dataType": "string",
            "sourceColumn": "lib_mod_gest",
            "summarizeBy": "none",
            "lineageTag": "6aa0fc90-3aa3-40f6-b64d-847978363425",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "enc_cnt_m",
            "dataType": "double",
            "sourceColumn": "enc_cnt_m",
            "summarizeBy": "sum",
            "lineageTag": "6223f0c2-eb26-4a17-a7bb-23a74fab72b6",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "enc_cnt_n1",
            "dataType": "double",
            "sourceColumn": "enc_cnt_n1",
            "summarizeBy": "sum",
            "lineageTag": "207f918c-293a-45cc-8bee-7cb78cd93425",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "col_brute",
            "dataType": "double",
            "sourceColumn": "col_brute",
            "summarizeBy": "sum",
            "lineageTag": "7ac3fe00-8f9e-4c1e-8af1-9e497a26862d",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "decollecte",
            "dataType": "double",
            "sourceColumn": "decollecte",
            "summarizeBy": "sum",
            "lineageTag": "ee7a6132-6398-4f0a-b430-18a0aeba5de6",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "col_nette",
            "dataType": "double",
            "sourceColumn": "col_nette",
            "summarizeBy": "sum",
            "lineageTag": "57b92784-dbab-4d9a-9534-9b94e92dbb0d",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "enc_fds_m",
            "dataType": "double",
            "sourceColumn": "enc_fds_m",
            "summarizeBy": "sum",
            "lineageTag": "2cdba3ce-66f6-4fc1-a9c3-c6510ae064f5",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "EPARGNE",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"E:\\\\louvre\\\\powerbi\\\\data\\\\EPARGNE.csv\"),[Delimiter=\",\", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),",
                "    #\"Promoted\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    #\"Typed\" = Table.TransformColumnTypes(#\"Promoted\", {{\"id_cli\", type text}, {\"num_cnt\", type text}, {\"perimetre\", type text}, {\"fam_pdt\", type text}, {\"lib_fds\", type text}, {\"isin_fds\", type text}, {\"lib_mod_gest\", type text}, {\"enc_cnt_m\", type number}, {\"enc_cnt_n1\", type number}, {\"col_brute\", type number}, {\"decollecte\", type number}, {\"col_nette\", type number}, {\"enc_fds_m\", type number}}, \"en-US\")",
                "in",
                "    #\"Typed\""
              ]
            }
          }
        ]
      },
      {
        "name": "CREDIT",
        "lineageTag": "8fba096e-0534-40c2-9d73-177a0fa4e8d6",
        "columns": [
          {
            "name": "id_cli",
            "dataType": "string",
            "sourceColumn": "id_cli",
            "summarizeBy": "none",
            "lineageTag": "69e1af5f-2771-4667-87be-482e97ea2c26",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "num_cnt",
            "dataType": "string",
            "sourceColumn": "num_cnt",
            "summarizeBy": "none",
            "lineageTag": "55dc2125-9cc5-4037-8ccd-ffd541b87aed",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "perimetre",
            "dataType": "string",
            "sourceColumn": "perimetre",
            "summarizeBy": "none",
            "lineageTag": "d9a51e7a-a5f8-43e2-9f72-fd93a46de45d",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Lib_Marche_Simple",
            "dataType": "string",
            "sourceColumn": "Lib_Marche_Simple",
            "summarizeBy": "none",
            "lineageTag": "e05275b3-d728-45f3-917a-a151bb4335d9",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "lib_typ_prt",
            "dataType": "string",
            "sourceColumn": "lib_typ_prt",
            "summarizeBy": "none",
            "lineageTag": "77768fe3-b73b-4f44-a92d-9b01d9012c91",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "enc_cpt",
            "dataType": "double",
            "sourceColumn": "enc_cpt",
            "summarizeBy": "sum",
            "lineageTag": "45b0a84a-b073-4887-a48f-f9c7cc8fd7c7",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "mnt_nom",
            "dataType": "double",
            "sourceColumn": "mnt_nom",
            "summarizeBy": "sum",
            "lineageTag": "3d1abccc-a30d-430e-9192-7bfe5784ddb8",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "mnt_krd_sain",
            "dataType": "double",
            "sourceColumn": "mnt_krd_sain",
            "summarizeBy": "sum",
            "lineageTag": "985862f0-35ae-4765-b961-02f7634a93d1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "mnt_krd_imp",
            "dataType": "double",
            "sourceColumn": "mnt_krd_imp",
            "summarizeBy": "sum",
            "lineageTag": "5fd77f34-1ac8-492f-aaf5-63400ef813a7",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "CREDIT",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"E:\\\\louvre\\\\powerbi\\\\data\\\\CREDIT.csv\"),[Delimiter=\",\", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),",
                "    #\"Promoted\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    #\"Typed\" = Table.TransformColumnTypes(#\"Promoted\", {{\"id_cli\", type text}, {\"num_cnt\", type text}, {\"perimetre\", type text}, {\"Lib_Marche_Simple\", type text}, {\"lib_typ_prt\", type text}, {\"enc_cpt\", type number}, {\"mnt_nom\", type number}, {\"mnt_krd_sain\", type number}, {\"mnt_krd_imp\", type number}}, \"en-US\")",
                "in",
                "    #\"Typed\""
              ]
            }
          }
        ]
      },
      {
        "name": "GARANTIE",
        "lineageTag": "f23087a3-a4b3-489a-a94a-1715db6b06fe",
        "columns": [
          {
            "name": "id_cli",
            "dataType": "string",
            "sourceColumn": "id_cli",
            "summarizeBy": "none",
            "lineageTag": "fe61a483-2b55-4ed7-82fe-28739779f6bc",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "num_cnt",
            "dataType": "string",
            "sourceColumn": "num_cnt",
            "summarizeBy": "none",
            "lineageTag": "48299771-d4a1-431b-8e08-5be5583a6fa4",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "det_typ_gar",
            "dataType": "string",
            "sourceColumn": "det_typ_gar",
            "summarizeBy": "none",
            "lineageTag": "28b1ffb4-f32e-45ea-9f81-8b93ca4c0268",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "mnt_gar",
            "dataType": "double",
            "sourceColumn": "mnt_gar",
            "summarizeBy": "sum",
            "lineageTag": "74e7ac14-cb02-42e5-b713-60f0b6683d81",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "mnt_gar_cpta",
            "dataType": "double",
            "sourceColumn": "mnt_gar_cpta",
            "summarizeBy": "sum",
            "lineageTag": "3a42b696-7b0d-4869-8d3f-9a62bf21bdb1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "GARANTIE",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"E:\\\\louvre\\\\powerbi\\\\data\\\\GARANTIE.csv\"),[Delimiter=\",\", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),",
                "    #\"Promoted\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    #\"Typed\" = Table.TransformColumnTypes(#\"Promoted\", {{\"id_cli\", type text}, {\"num_cnt\", type text}, {\"det_typ_gar\", type text}, {\"mnt_gar\", type number}, {\"mnt_gar_cpta\", type number}}, \"en-US\")",
                "in",
                "    #\"Typed\""
              ]
            }
          }
        ]
      },
      {
        "name": "SERVICE",
        "lineageTag": "4d5692b8-6af9-47ac-9bd4-b5de43d4532e",
        "columns": [
          {
            "name": "id_cli",
            "dataType": "string",
            "sourceColumn": "id_cli",
            "summarizeBy": "none",
            "lineageTag": "df63e562-f0f8-4372-baa7-3740bc58b794",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "num_cnt",
            "dataType": "string",
            "sourceColumn": "num_cnt",
            "summarizeBy": "none",
            "lineageTag": "ee01b9fb-0afc-486b-96e2-d12df208d031",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "fam_pdt",
            "dataType": "string",
            "sourceColumn": "fam_pdt",
            "summarizeBy": "none",
            "lineageTag": "5294c4af-ed2f-4f02-9684-afcdc62c2a6b",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "mnt_tar_brt",
            "dataType": "double",
            "sourceColumn": "mnt_tar_brt",
            "summarizeBy": "sum",
            "lineageTag": "dd4d941d-dc09-469f-9fcd-a0bfe83c6063",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "SERVICE",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"E:\\\\louvre\\\\powerbi\\\\data\\\\SERVICE.csv\"),[Delimiter=\",\", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),",
                "    #\"Promoted\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    #\"Typed\" = Table.TransformColumnTypes(#\"Promoted\", {{\"id_cli\", type text}, {\"num_cnt\", type text}, {\"fam_pdt\", type text}, {\"mnt_tar_brt\", type number}}, \"en-US\")",
                "in",
                "    #\"Typed\""
              ]
            }
          }
        ]
      },
      {
        "name": "GSM",
        "lineageTag": "11822a79-649e-4f29-bd85-9ed90cedbd95",
        "columns": [
          {
            "name": "isin_fds",
            "dataType": "string",
            "sourceColumn": "isin_fds",
            "summarizeBy": "none",
            "lineageTag": "767d411d-6862-49da-9cce-096793214d4e",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Classification_SFDR",
            "dataType": "string",
            "sourceColumn": "Classification_SFDR",
            "summarizeBy": "none",
            "lineageTag": "1aa8d82b-53a8-483f-a792-c6a2a04064be",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "enc_fds_m",
            "dataType": "double",
            "sourceColumn": "enc_fds_m",
            "summarizeBy": "sum",
            "lineageTag": "12ba5b85-37af-482b-8ff8-dfd69e802d89",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "performance_cli",
            "dataType": "double",
            "sourceColumn": "performance_cli",
            "summarizeBy": "sum",
            "lineageTag": "82a4fc6a-b83f-4a39-8672-4bfb43a2343b",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "GSM",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"E:\\\\louvre\\\\powerbi\\\\data\\\\GSM.csv\"),[Delimiter=\",\", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),",
                "    #\"Promoted\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    #\"Typed\" = Table.TransformColumnTypes(#\"Promoted\", {{\"isin_fds\", type text}, {\"Classification_SFDR\", type text}, {\"enc_fds_m\", type number}, {\"performance_cli\", type number}}, \"en-US\")",
                "in",
                "    #\"Typed\""
              ]
            }
          }
        ]
      },
      {
        "name": "_M_Dashboard",
        "lineageTag": "72e3a67c-156b-4a43-948b-fa32734dd38a",
        "isHidden": true,
        "columns": [
          {
            "name": "Column1",
            "dataType": "string",
            "sourceColumn": "Column1",
            "isHidden": true,
            "summarizeBy": "none",
            "lineageTag": "1637d590-0f45-4e70-a70b-04dd00669389",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "_M_Dashboard",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": "let\n    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i44FAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text)) in type table [ Column1 = _t ])\nin\n    Source"
            }
          }
        ],
        "measures": [
          {
            "name": "Nb Clients Totaux",
            "expression": "CALCULATE(DISTINCTCOUNT(CLIENT[id_cli]), CLIENT[cli_c_p] IN {\"CL\",\"CT\"})",
            "lineageTag": "3d723133-4392-499c-bbda-82ef7e87de49",
            "formatString": "#,0"
          },
          {
            "name": "Nb Clients Actifs",
            "expression": "CALCULATE(DISTINCTCOUNT(CLIENT[id_cli]), CLIENT[top_client_actif]=\"O\")",
            "lineageTag": "1d684513-a47c-4389-b4ee-bb4fec0ec686",
            "formatString": "#,0"
          },
          {
            "name": "Nb Prospects",
            "expression": "CALCULATE(DISTINCTCOUNT(CLIENT[id_cli]), CLIENT[cli_c_p]=\"PR\")",
            "lineageTag": "b5d65310-f804-4764-bd81-a5d6803611d2",
            "formatString": "#,0"
          },
          {
            "name": "Nb Clients Enrollés",
            "expression": "CALCULATE(DISTINCTCOUNT(CLIENT[id_cli]), CLIENT[nb_dev_enrol]>0)",
            "lineageTag": "404a6061-a4ac-4c85-a01a-2b80af34f275",
            "formatString": "#,0"
          },
          {
            "name": "Taux Enrollment",
            "expression": "DIVIDE([Nb Clients Enrollés],[Nb Clients Totaux],0)",
            "lineageTag": "1cf412c6-0fac-4f0d-88af-1b84f449f07a",
            "formatString": "0.0%"
          },
          {
            "name": "Taux Clients Actifs",
            "expression": "DIVIDE([Nb Clients Actifs],[Nb Clients Totaux],0)",
            "lineageTag": "2b84f7d2-ab97-4922-9ec5-93acb17ec613",
            "formatString": "0.0%"
          },
          {
            "name": "Nb Smartphones",
            "expression": "SUM(CLIENT[nb_dev_enrol])",
            "lineageTag": "eeca4c07-563e-4dcb-bbb0-49839d4a64fe",
            "formatString": "#,0"
          },
          {
            "name": "Nb Comptes Bloqués",
            "expression": "CALCULATE(DISTINCTCOUNT(CLIENT[id_cli]), CLIENT[etat_acc]=\"B\")",
            "lineageTag": "2a31a056-6464-4e37-8977-0cb7b26c7110",
            "formatString": "#,0"
          },
          {
            "name": "Nb Comptes Suspendus",
            "expression": "CALCULATE(DISTINCTCOUNT(CLIENT[id_cli]), CLIENT[etat_acc]=\"S\")",
            "lineageTag": "2d1c45be-edcb-4fb0-9455-d41e6020df1d",
            "formatString": "#,0"
          },
          {
            "name": "Nb Agences",
            "expression": "DISTINCTCOUNT(CLIENT[agc_topz])",
            "lineageTag": "016fdfd3-dcdd-4b4a-a1f4-16acea77dcea",
            "formatString": "#,0"
          },
          {
            "name": "Nb Pays",
            "expression": "DISTINCTCOUNT(CLIENT[pay_res])",
            "lineageTag": "35e918fb-ba5a-4ffb-bce8-7ee6929d63db",
            "formatString": "#,0"
          },
          {
            "name": "AUM Total",
            "expression": "SUM(CLIENT[aum_tit])",
            "lineageTag": "e5ad31ca-ea51-4faf-ae27-17fb162b9fb7",
            "formatString": "#,0 €"
          },
          {
            "name": "AUM Moyen",
            "expression": "DIVIDE([AUM Total],[Nb Clients Totaux],0)",
            "lineageTag": "5c3a2e1a-e2d7-41d4-b938-f172b5482678",
            "formatString": "#,0 €"
          },
          {
            "name": "Encours Épargne",
            "expression": "CALCULATE(SUM(EPARGNE[enc_cnt_m]), EPARGNE[perimetre]=\"epargne\")",
            "lineageTag": "38371fc0-353c-4689-9a5c-c84bcbbfeac0",
            "formatString": "#,0 €"
          },
          {
            "name": "Encours Fonds",
            "expression": "SUM(EPARGNE[enc_fds_m])",
            "lineageTag": "913f6b25-ff4e-4aaa-af2c-16b798494928",
            "formatString": "#,0 €"
          },
          {
            "name": "Encours Crédit Total",
            "expression": "SUM(CREDIT[enc_cpt])",
            "lineageTag": "ab911035-57eb-4684-89d3-bbfb96248124",
            "formatString": "#,0 €"
          },
          {
            "name": "Capital Sain",
            "expression": "SUM(CREDIT[mnt_krd_sain])",
            "lineageTag": "47fa89f7-f6cf-4260-995c-45cb2e4573dc",
            "formatString": "#,0 €"
          },
          {
            "name": "Capital Impayé",
            "expression": "SUM(CREDIT[mnt_krd_imp])",
            "lineageTag": "b9677333-eadc-4144-be49-f7baa61afa91",
            "formatString": "#,0 €"
          },
          {
            "name": "Collecte Brute",
            "expression": "CALCULATE(SUM(EPARGNE[col_brute]), EPARGNE[perimetre]=\"epargne\")",
            "lineageTag": "bb769b73-511d-4fa1-8008-af61245288f3",
            "formatString": "#,0 €"
          },
          {
            "name": "Décollecte",
            "expression": "CALCULATE(SUM(EPARGNE[decollecte]), EPARGNE[perimetre]=\"epargne\")",
            "lineageTag": "f68c2525-1deb-4ded-8a14-89eda9805f42",
            "formatString": "#,0 €"
          },
          {
            "name": "Collecte Nette",
            "expression": "CALCULATE(SUM(EPARGNE[col_nette]), EPARGNE[perimetre]=\"epargne\")",
            "lineageTag": "a1d70341-64e4-4e2a-9699-ceedf68855a2",
            "formatString": "#,0 €"
          },
          {
            "name": "Volume Transactions",
            "expression": "SUM('TRANSACTION'[mnt_evt])",
            "lineageTag": "5d07214f-ffa1-4a90-9299-e189854b63ec",
            "formatString": "#,0 €"
          },
          {
            "name": "Nb Transactions",
            "expression": "COUNTROWS('TRANSACTION')",
            "lineageTag": "d99ccb52-3095-4b2d-865c-b62ae920e267",
            "formatString": "#,0"
          },
          {
            "name": "Nb Transactions Sensibles",
            "expression": "CALCULATE(COUNTROWS('TRANSACTION'), 'TRANSACTION'[Transaction_Sensible]=1)",
            "lineageTag": "a185d25d-cca5-4180-8b0f-faa035a43586",
            "formatString": "#,0"
          },
          {
            "name": "Volume Tx Sensibles",
            "expression": "CALCULATE(SUM('TRANSACTION'[mnt_evt]), 'TRANSACTION'[Transaction_Sensible]=1)",
            "lineageTag": "4627b236-6dc8-4384-82b2-cdd806a3e506",
            "formatString": "#,0 €"
          },
          {
            "name": "Clients Sensibles",
            "expression": "CALCULATE(DISTINCTCOUNT(CLIENT[id_cli]), CLIENT[cd_risque_pers] IN {\"E\",\"F\"})",
            "lineageTag": "c76a0688-3ba9-4b52-b91b-58335abc83dc",
            "formatString": "#,0"
          },
          {
            "name": "Nb KYC Rouge",
            "expression": "CALCULATE(DISTINCTCOUNT(CLIENT[id_cli]), CLIENT[gelule_global]=10)",
            "lineageTag": "4d70d911-c748-4865-b4d2-0f8c9b67b4ae",
            "formatString": "#,0"
          },
          {
            "name": "Nb KYC Orange",
            "expression": "CALCULATE(DISTINCTCOUNT(CLIENT[id_cli]), CLIENT[gelule_global]=5)",
            "lineageTag": "13885494-f59b-42da-96d0-882c0e5a08c3",
            "formatString": "#,0"
          },
          {
            "name": "Taux Conformité KYC",
            "expression": "DIVIDE(CALCULATE(DISTINCTCOUNT(CLIENT[id_cli]),CLIENT[gelule_global]=0),[Nb Clients Totaux],0)",
            "lineageTag": "c512262c-8edf-41ee-a7ce-bc226d686487",
            "formatString": "0.0%"
          },
          {
            "name": "Date Fonctionnelle",
            "expression": "\"Données arrêtées au \" & FORMAT(MAX(CLIENT[dt_fonc]),\"DD/MM/YYYY\")",
            "lineageTag": "08a27795-8e12-4b74-aa0a-8ca5181be42b"
          }
        ]
      }
    ],
    "relationships": [
      {
        "name": "a59fefb5-48f0-4df2-b472-c7e5441fd7a9",
        "fromTable": "TRANSACTION",
        "fromColumn": "id_cli",
        "toTable": "CLIENT",
        "toColumn": "id_cli",
        "crossFilteringBehavior": "oneDirection"
      },
      {
        "name": "4646b3f4-adb1-426b-9d95-d093f43b8884",
        "fromTable": "EPARGNE",
        "fromColumn": "id_cli",
        "toTable": "CLIENT",
        "toColumn": "id_cli",
        "crossFilteringBehavior": "oneDirection"
      },
      {
        "name": "6991532f-2907-4eb7-8089-3004847cfa36",
        "fromTable": "CREDIT",
        "fromColumn": "id_cli",
        "toTable": "CLIENT",
        "toColumn": "id_cli",
        "crossFilteringBehavior": "oneDirection"
      },
      {
        "name": "b93dbd50-4da7-4fe2-ab82-28d9a5650369",
        "fromTable": "SERVICE",
        "fromColumn": "id_cli",
        "toTable": "CLIENT",
        "toColumn": "id_cli",
        "crossFilteringBehavior": "oneDirection"
      },
      {
        "name": "36d37371-dc97-42f6-80d4-bda4dbb89ff3",
        "fromTable": "GARANTIE",
        "fromColumn": "id_cli",
        "toTable": "CLIENT",
        "toColumn": "id_cli",
        "crossFilteringBehavior": "oneDirection",
        "isActive": false
      },
      {
        "name": "46bfb1bd-d648-4f97-886f-a579c30bab3f",
        "fromTable": "GARANTIE",
        "fromColumn": "num_cnt",
        "toTable": "CREDIT",
        "toColumn": "num_cnt",
        "crossFilteringBehavior": "oneDirection"
      }
    ],
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"CLIENT\", \"TRANSACTION\", \"EPARGNE\", \"CREDIT\", \"GARANTIE\", \"SERVICE\", \"GSM\"]"
      }
    ]
  }
}