table _M_Dashboard
	isHidden
	lineageTag: fb9e25f2-8d8d-49d5-8146-418c7baf8d58

	measure 'Nb Clients Totaux' = CALCULATE(DISTINCTCOUNT(CLIENT[id_cli]), CLIENT[cli_c_p] IN {"CL","CT"})
		formatString: #,0
		lineageTag: ae3d4b93-b91e-4281-a28d-933a6522b614

	measure 'Nb Clients Actifs' = CALCULATE(DISTINCTCOUNT(CLIENT[id_cli]), CLIENT[top_client_actif]="O")
		formatString: #,0
		lineageTag: 2d811495-9802-4c5f-93c7-ad6ae2371192

	measure 'Nb Prospects' = CALCULATE(DISTINCTCOUNT(CLIENT[id_cli]), CLIENT[cli_c_p]="PR")
		formatString: #,0
		lineageTag: 56241a1b-b0f4-4ff9-ac56-eab52c29183f

	measure 'Nb Clients Enrollés' = CALCULATE(DISTINCTCOUNT(CLIENT[id_cli]), CLIENT[nb_dev_enrol]>0)
		formatString: #,0
		lineageTag: 1eb22678-8f08-438f-ac5b-b6f28b498775

	measure 'Taux Enrollment' = DIVIDE([Nb Clients Enrollés],[Nb Clients Totaux],0)
		formatString: 0.0%
		lineageTag: 0167198e-0846-4dc1-b0ff-2024860fb671

	measure 'Taux Clients Actifs' = DIVIDE([Nb Clients Actifs],[Nb Clients Totaux],0)
		formatString: 0.0%
		lineageTag: 98479705-4a63-43e3-9543-f61ac79f4838

	measure 'Nb Smartphones' = SUM(CLIENT[nb_dev_enrol])
		formatString: #,0
		lineageTag: 3f9ddf15-b6b5-4535-b382-628df22daf95

	measure 'Nb Comptes Bloqués' = CALCULATE(DISTINCTCOUNT(CLIENT[id_cli]), CLIENT[etat_acc]="B")
		formatString: #,0
		lineageTag: fe50ad68-05bf-4c9c-bb2e-5d245eb4d607

	measure 'Nb Comptes Suspendus' = CALCULATE(DISTINCTCOUNT(CLIENT[id_cli]), CLIENT[etat_acc]="S")
		formatString: #,0
		lineageTag: ec85ef78-037f-4973-85eb-47ddb433d22b

	measure 'Nb Agences' = DISTINCTCOUNT(CLIENT[agc_topz])
		formatString: #,0
		lineageTag: f52a8de3-420f-4fae-8359-20e7dd4f1aed

	measure 'Nb Pays' = DISTINCTCOUNT(CLIENT[pay_res])
		formatString: #,0
		lineageTag: 484aa5de-6072-4943-8194-030387658adc

	measure 'AUM Total' = SUM(CLIENT[aum_tit])
		formatString: #,0 €
		lineageTag: 555436aa-1ce4-42af-83e4-11b2512fe560

	measure 'AUM Moyen' = DIVIDE([AUM Total],[Nb Clients Totaux],0)
		formatString: #,0 €
		lineageTag: 895e9df7-951a-4791-a7b8-c3e38399d24c

	measure 'Encours Épargne' = CALCULATE(SUM(EPARGNE[enc_cnt_m]), EPARGNE[perimetre]="epargne")
		formatString: #,0 €
		lineageTag: f2db58db-3003-4221-bace-4d3a2a10bcca

	measure 'Encours Fonds' = SUM(EPARGNE[enc_fds_m])
		formatString: #,0 €
		lineageTag: cfe98b8f-bd31-44d6-ba91-32f780b3177e

	measure 'Encours Crédit Total' = SUM(CREDIT[enc_cpt])
		formatString: #,0 €
		lineageTag: 206900bc-ef1a-4948-8d9a-d8e8ae4ccdb3

	measure 'Capital Sain' = SUM(CREDIT[mnt_krd_sain])
		formatString: #,0 €
		lineageTag: 17f3c584-c052-441c-8971-bcbad798474c

	measure 'Capital Impayé' = SUM(CREDIT[mnt_krd_imp])
		formatString: #,0 €
		lineageTag: a7098ff7-0ebc-486c-b22a-cb60cbaf48a5

	measure 'Nb Crédits' = DISTINCTCOUNT(CREDIT[num_cnt])
		formatString: #,0
		lineageTag: 06b7e928-e15b-49c3-b817-31bf0f5a27ca

	measure 'Montant Nominal' = SUM(CREDIT[mnt_nom])
		formatString: #,0 €
		lineageTag: 8304c037-2450-49a5-a35d-4ede39ad47fa

	measure 'Montant Débloqué' = SUM(CREDIT[mnt_dblq])
		formatString: #,0 €
		lineageTag: c9609246-d903-4459-b888-fc7751e7c2b9

	measure 'Reste à Débloquer' = SUM(CREDIT[mnt_disp])
		formatString: #,0 €
		lineageTag: d575baa0-fc6c-4067-b0e3-762b38c95f7b

	measure 'Taux Impayés' = DIVIDE(SUM(CREDIT[mnt_krd_imp]),SUM(CREDIT[mnt_krd_tot]),0)
		formatString: 0.0%
		lineageTag: 3cc793f5-9380-4bbb-8c40-d94443c8507f

	measure 'LTV Moyenne' = AVERAGEX(FILTER(CREDIT,CREDIT[ltv_act]>0),CREDIT[ltv_act])
		formatString: 0.0%
		lineageTag: 7b425e4d-8863-4098-82fd-a412fff826d3

	measure 'TEG Moyen' = AVERAGEX(FILTER(CREDIT,CREDIT[teg]>0),CREDIT[teg])
		formatString: 0.00%
		lineageTag: 8f4aaee4-0ad4-449f-9b7e-96c349a06cde

	measure 'Provisions IFRS9 Crédit' = SUM(CREDIT[mnt_prov_b_ifrs9])+SUM(CREDIT[mnt_prov_hb_ifrs9])
		formatString: #,0 €
		lineageTag: 588c254d-4146-4804-bef3-d26d52482149

	measure 'RWA Crédit' = SUM(CREDIT[total_rwa])
		formatString: #,0 €
		lineageTag: a9c7c56c-53a7-486e-b3f3-b8768dd0e13d

	measure 'Montant Garanties' = SUM(GARANTIE[mnt_gar])
		formatString: #,0 €
		lineageTag: 587e3a41-5b50-4c21-98de-0fdf5ef8c846

	measure 'Taux Couverture Garanties' = DIVIDE(SUM(GARANTIE[mnt_gar_cpta]),[Encours Crédit Total],0)
		formatString: 0.0%
		lineageTag: 18f11d63-d4cc-4d4c-9bd8-8b704effb8d7

	measure 'Collecte Brute' = CALCULATE(SUM(EPARGNE[col_brute]), EPARGNE[perimetre]="epargne")
		formatString: #,0 €
		lineageTag: 826ed5f1-c750-4fac-9d49-7045cd91159e

	measure Décollecte = CALCULATE(SUM(EPARGNE[decollecte]), EPARGNE[perimetre]="epargne")
		formatString: #,0 €
		lineageTag: 132310fb-0a65-4b81-910d-26e0d84a75ec

	measure 'Collecte Nette' = CALCULATE(SUM(EPARGNE[col_nette]), EPARGNE[perimetre]="epargne")
		formatString: #,0 €
		lineageTag: 74974d3e-0d94-4ffe-b2ea-36ba8f089b31

	measure 'Volume Transactions' = SUM('TRANSACTION'[mnt_evt])
		formatString: #,0 €
		lineageTag: 6612e2c1-b6c7-4c9d-b770-d0fe4f9d6bd3

	measure 'Nb Transactions' = COUNTROWS('TRANSACTION')
		formatString: #,0
		lineageTag: 4e18bd4d-f247-46ba-88f6-14f39d0c0403

	measure 'Nb Transactions Sensibles' = CALCULATE(COUNTROWS('TRANSACTION'), 'TRANSACTION'[Transaction_Sensible]=1)
		formatString: #,0
		lineageTag: 7812b1c1-6efe-421e-bf11-a27aa78cf0b9

	measure 'Volume Tx Sensibles' = CALCULATE(SUM('TRANSACTION'[mnt_evt]), 'TRANSACTION'[Transaction_Sensible]=1)
		formatString: #,0 €
		lineageTag: 9b6422c4-43d3-489b-b1ce-50f5fb3d00ae

	measure 'Clients Sensibles' = CALCULATE(DISTINCTCOUNT(CLIENT[id_cli]), CLIENT[cd_risque_pers] IN {"E","F"})
		formatString: #,0
		lineageTag: 057712e4-d887-46c1-b5fe-dc83592c8f22

	measure 'Nb KYC Rouge' = CALCULATE(DISTINCTCOUNT(CLIENT[id_cli]), CLIENT[gelule_global]=10)
		formatString: #,0
		lineageTag: 6e77acc4-cc33-414b-b6b8-8e6ddb11858a

	measure 'Nb KYC Orange' = CALCULATE(DISTINCTCOUNT(CLIENT[id_cli]), CLIENT[gelule_global]=5)
		formatString: #,0
		lineageTag: c42f04e1-4721-403d-ab9b-336beb3c8ead

	measure 'Taux Conformité KYC' = DIVIDE(CALCULATE(DISTINCTCOUNT(CLIENT[id_cli]),CLIENT[gelule_global]=0),[Nb Clients Totaux],0)
		formatString: 0.0%
		lineageTag: 6dbf3a1d-c60b-427d-8344-d9c599511f0b

	measure 'Date Fonctionnelle' = "Données arrêtées au " & FORMAT(MAX(CLIENT[dt_fonc]),"DD/MM/YYYY")
		lineageTag: 597dd4be-90fa-4f3a-b9dc-766ce25f9dcb

	column Column1
		dataType: string
		isHidden
		lineageTag: 0d78bc11-8acf-4543-ad37-6403e77f88df
		summarizeBy: none
		sourceColumn: Column1

		annotation SummarizationSetBy = Automatic

	partition _M_Dashboard = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text)) in type table [ Column1 = _t ])
				in
				    Source

