table CLIENT
	lineageTag: d8acd438-ddf7-4bde-8b7a-fb18f20b994f

	column id_cli
		dataType: string
		lineageTag: 9314a242-555d-41a4-a7d0-a239cee1f1c3
		summarizeBy: none
		sourceColumn: id_cli

		annotation SummarizationSetBy = Automatic

	column cli_c_p
		dataType: string
		lineageTag: 81fd0c95-e368-47d6-928b-2f4c7afdb730
		summarizeBy: none
		sourceColumn: cli_c_p

		annotation SummarizationSetBy = Automatic

	column nom_cplt
		dataType: string
		lineageTag: e0d34d10-9e01-43f6-9792-2f73c763bbfa
		summarizeBy: none
		sourceColumn: nom_cplt

		annotation SummarizationSetBy = Automatic

	column lib_cd_typ
		dataType: string
		lineageTag: 23d8b645-5fe5-4d91-b4c6-a6df1d261879
		summarizeBy: none
		sourceColumn: lib_cd_typ

		annotation SummarizationSetBy = Automatic

	column lib_gr
		dataType: string
		lineageTag: 591f6f22-f06f-4707-bb27-6d136ffefe3c
		summarizeBy: none
		sourceColumn: lib_gr

		annotation SummarizationSetBy = Automatic

	column agc_topz
		dataType: string
		lineageTag: 298a32fb-158c-4bd4-a36b-93684b77d0b0
		summarizeBy: none
		sourceColumn: agc_topz

		annotation SummarizationSetBy = Automatic

	column lib_ptf
		dataType: string
		lineageTag: 6d1b15b1-7c94-4147-96c5-a63a095449db
		summarizeBy: none
		sourceColumn: lib_ptf

		annotation SummarizationSetBy = Automatic

	column nom_cons
		dataType: string
		lineageTag: b1a13df6-e585-498d-ab75-5346e2d27853
		summarizeBy: none
		sourceColumn: nom_cons

		annotation SummarizationSetBy = Automatic

	column pay_res
		dataType: string
		lineageTag: b1009ebb-359a-402f-92ad-a0e2b282e235
		summarizeBy: none
		sourceColumn: pay_res

		annotation SummarizationSetBy = Automatic

	column lib_pay_res
		dataType: string
		lineageTag: c023e4c7-5bcb-4f4a-96ae-9d01e5efb0f8
		summarizeBy: none
		sourceColumn: lib_pay_res

		annotation SummarizationSetBy = Automatic

	column couleur_pays
		dataType: string
		lineageTag: 95cf7a79-ec61-4bb1-98ab-b8924ce84341
		summarizeBy: none
		sourceColumn: couleur_pays

		annotation SummarizationSetBy = Automatic

	column lib_cd_risque_pers
		dataType: string
		lineageTag: dd1aa33c-d2bb-44b1-85f6-efafbb9fc8e2
		summarizeBy: none
		sourceColumn: lib_cd_risque_pers

		annotation SummarizationSetBy = Automatic

	column cd_risque_pers
		dataType: string
		lineageTag: a43c216b-0bc8-4e05-9607-15b468060f65
		summarizeBy: none
		sourceColumn: cd_risque_pers

		annotation SummarizationSetBy = Automatic

	column etat_acc
		dataType: string
		lineageTag: 0b3974d2-5c8f-40da-ae64-96153130e952
		summarizeBy: none
		sourceColumn: etat_acc

		annotation SummarizationSetBy = Automatic

	column top_client_actif
		dataType: string
		lineageTag: 974c1422-fa80-4b61-b479-084aa0cd8826
		summarizeBy: none
		sourceColumn: top_client_actif

		annotation SummarizationSetBy = Automatic

	column typ_enrol
		dataType: string
		lineageTag: c98dcb4b-ce52-4df9-bdcf-5f60f37c6172
		summarizeBy: none
		sourceColumn: typ_enrol

		annotation SummarizationSetBy = Automatic

	column gelule_global
		dataType: int64
		lineageTag: 897b3ad4-a39c-417c-b59e-2bef52828b37
		summarizeBy: sum
		sourceColumn: gelule_global

		annotation SummarizationSetBy = Automatic

	column nb_dev_enrol
		dataType: int64
		lineageTag: 3891863a-5f43-49c4-b7b9-f685196bd8ad
		summarizeBy: sum
		sourceColumn: nb_dev_enrol

		annotation SummarizationSetBy = Automatic

	column age_cli
		dataType: int64
		lineageTag: 6e17e7dd-bb55-4b24-9b53-1b577cc08769
		summarizeBy: sum
		sourceColumn: age_cli

		annotation SummarizationSetBy = Automatic

	column dt_enrol
		dataType: dateTime
		formatString: Long Date
		lineageTag: abdf3a41-de66-45c3-9dac-b95a4b0e79ba
		summarizeBy: none
		sourceColumn: dt_enrol

		variation Variation
			isDefault
			relationship: e34e470f-80b1-4b52-9ade-1bec54aea6ad
			defaultHierarchy: LocalDateTable_be6ff19e-2879-4941-8f52-2116fb02e18e.'Hiérarchie de dates'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column dt_der_cnx
		dataType: dateTime
		formatString: Long Date
		lineageTag: 1254c3ec-cfae-40ee-9790-f0454917df78
		summarizeBy: none
		sourceColumn: dt_der_cnx

		variation Variation
			isDefault
			relationship: 2883886a-6d6c-41f9-95ae-a07695e39c25
			defaultHierarchy: LocalDateTable_12081caa-9f24-4891-b4db-334513dcc235.'Hiérarchie de dates'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column dt_fonc
		dataType: dateTime
		formatString: Long Date
		lineageTag: c56d4459-1f16-4b40-a39e-9923cb3edbdf
		summarizeBy: none
		sourceColumn: dt_fonc

		variation Variation
			isDefault
			relationship: 72a5054a-a442-4332-aa0e-fce836e56f2c
			defaultHierarchy: LocalDateTable_496e8fdc-e07e-4732-87ed-6acf01dbb6e0.'Hiérarchie de dates'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column aum_tit
		dataType: double
		lineageTag: 594e09e5-795b-4a33-9629-0573b59f4b9d
		summarizeBy: sum
		sourceColumn: aum_tit

		annotation SummarizationSetBy = Automatic

	column aum_cot
		dataType: double
		lineageTag: cdcadf70-c274-4f2a-81d8-fc2b10e2f274
		summarizeBy: sum
		sourceColumn: aum_cot

		annotation SummarizationSetBy = Automatic

	column mnt_pat_epargne
		dataType: double
		lineageTag: 2806a221-d73c-4adc-9f51-647bc9ba9f3b
		summarizeBy: sum
		sourceColumn: mnt_pat_epargne

		annotation SummarizationSetBy = Automatic

	column mnt_rev_princ
		dataType: double
		lineageTag: 0194610d-5be4-4e76-8a9f-b8cc7c79cebc
		summarizeBy: sum
		sourceColumn: mnt_rev_princ

		annotation SummarizationSetBy = Automatic

	column cd_typ
		dataType: string
		lineageTag: 7edeb6c3-5031-422f-808e-f6b122b6669c
		summarizeBy: none
		sourceColumn: cd_typ

		annotation SummarizationSetBy = Automatic

	column id_gr
		dataType: string
		lineageTag: b67306d8-0293-4255-a38d-a6722fa32ce3
		summarizeBy: none
		sourceColumn: id_gr

		annotation SummarizationSetBy = Automatic

	column prm_prn
		dataType: string
		lineageTag: 2be164d5-5820-441d-9289-45e240ef736e
		summarizeBy: none
		sourceColumn: prm_prn

		annotation SummarizationSetBy = Automatic

	column nom_us
		dataType: string
		lineageTag: 405e54d3-9a22-4867-8ff3-d00ce2ccc5c8
		summarizeBy: none
		sourceColumn: nom_us

		annotation SummarizationSetBy = Automatic

	column cd_situ_fam
		dataType: string
		lineageTag: c0f45fb9-37a9-4088-b1c8-8713c3e00721
		summarizeBy: none
		sourceColumn: cd_situ_fam

		annotation SummarizationSetBy = Automatic

	column lib_cd_situ_fam
		dataType: string
		lineageTag: 517257ef-3302-4fb0-9083-c4381fd72c69
		summarizeBy: none
		sourceColumn: lib_cd_situ_fam

		annotation SummarizationSetBy = Automatic

	column cd_cons
		dataType: string
		lineageTag: 04402136-0c5d-42eb-8aa5-7abe6bb0b685
		summarizeBy: none
		sourceColumn: cd_cons

		annotation SummarizationSetBy = Automatic

	column prm_cons
		dataType: string
		lineageTag: fd8bee25-88d6-4bcc-afdb-fe1ad6e8c43b
		summarizeBy: none
		sourceColumn: prm_cons

		annotation SummarizationSetBy = Automatic

	column lib_grp_agce
		dataType: string
		lineageTag: 93b9be96-8c65-4a90-bb1c-bd5ee8a06da8
		summarizeBy: none
		sourceColumn: lib_grp_agce

		annotation SummarizationSetBy = Automatic

	column dt_top_cl
		dataType: string
		lineageTag: 0f8899a3-4cc7-4946-8f3d-b0c30968b9a8
		summarizeBy: none
		sourceColumn: dt_top_cl

		annotation SummarizationSetBy = Automatic

	column dt_exit_cl
		dataType: string
		lineageTag: 045cb624-282d-4b8e-b952-4370fcd5a8c9
		summarizeBy: none
		sourceColumn: dt_exit_cl

		annotation SummarizationSetBy = Automatic

	column dt_dernier_rdv
		dataType: string
		lineageTag: 653bf134-b87f-437b-b3ad-301d7c99c925
		summarizeBy: none
		sourceColumn: dt_dernier_rdv

		annotation SummarizationSetBy = Automatic

	column dt_1er_cnt
		dataType: string
		lineageTag: 61663ac6-b525-4acf-8562-8d81cd7afc8e
		summarizeBy: none
		sourceColumn: dt_1er_cnt

		annotation SummarizationSetBy = Automatic

	column cd_risque_ajust
		dataType: string
		lineageTag: ac4d4301-db25-4187-896b-fd1d4ea89f02
		summarizeBy: none
		sourceColumn: cd_risque_ajust

		annotation SummarizationSetBy = Automatic

	column lib_cd_risque_ajust
		dataType: string
		lineageTag: 4ea1ec01-98d5-45e0-a3aa-57002c7dd254
		summarizeBy: none
		sourceColumn: lib_cd_risque_ajust

		annotation SummarizationSetBy = Automatic

	column tot_score_risque
		dataType: string
		lineageTag: f1e0ee08-93b5-43cb-a3f8-fc1528893668
		summarizeBy: none
		sourceColumn: tot_score_risque

		annotation SummarizationSetBy = Automatic

	column scenario_risque
		dataType: string
		lineageTag: 421cff0c-05ea-4c2b-a895-0e14f09422b2
		summarizeBy: none
		sourceColumn: scenario_risque

		annotation SummarizationSetBy = Automatic

	column lib_scenario_risque
		dataType: string
		lineageTag: 8cdd19f6-a7f4-4e1f-b216-94519be8e394
		summarizeBy: none
		sourceColumn: lib_scenario_risque

		annotation SummarizationSetBy = Automatic

	column cd_mf
		dataType: string
		lineageTag: a457f857-7b60-4af1-b5b0-ac60baca26d2
		summarizeBy: none
		sourceColumn: cd_mf

		annotation SummarizationSetBy = Automatic

	column lib_gelule_global
		dataType: string
		lineageTag: 57ba00e1-314b-4821-bd8d-8d3cab14a8c9
		summarizeBy: none
		sourceColumn: lib_gelule_global

		annotation SummarizationSetBy = Automatic

	column kyc_idt
		dataType: string
		lineageTag: 7eb0825b-ecb2-4d9e-b42b-658199b1d0f7
		summarizeBy: none
		sourceColumn: kyc_idt

		annotation SummarizationSetBy = Automatic

	column kyc_adr
		dataType: string
		lineageTag: d44343aa-0520-40c5-b688-d6d7b6fa7c4f
		summarizeBy: none
		sourceColumn: kyc_adr

		annotation SummarizationSetBy = Automatic

	column dt_der_certif
		dataType: string
		lineageTag: b66d024d-d7d9-424e-8930-f8f23ff4bfea
		summarizeBy: none
		sourceColumn: dt_der_certif

		annotation SummarizationSetBy = Automatic

	column dt_next_certif
		dataType: string
		lineageTag: b3448e39-b0f2-41e6-bf17-762aa2fd72fe
		summarizeBy: none
		sourceColumn: dt_next_certif

		annotation SummarizationSetBy = Automatic

	column lib_stt_fatca
		dataType: string
		lineageTag: 8e79d212-d771-4cd5-a035-7f1f2e3cefff
		summarizeBy: none
		sourceColumn: lib_stt_fatca

		annotation SummarizationSetBy = Automatic

	column pay_fis_prin
		dataType: string
		lineageTag: d0e8dad8-3d6d-4100-abeb-9067868ff7ce
		summarizeBy: none
		sourceColumn: pay_fis_prin

		annotation SummarizationSetBy = Automatic

	column niveau_risque_pays
		dataType: string
		lineageTag: 0c88be1f-af95-4107-a4a4-a2fe1d91c645
		summarizeBy: none
		sourceColumn: niveau_risque_pays

		annotation SummarizationSetBy = Automatic

	column top_pays_embargo
		dataType: string
		lineageTag: 0e09c302-7e99-48d0-b927-3dd5fb64ffac
		summarizeBy: none
		sourceColumn: top_pays_embargo

		annotation SummarizationSetBy = Automatic

	column top_pays_sanctions
		dataType: string
		lineageTag: 78240dbb-23de-4ad8-9973-5c8a41a6f9cf
		summarizeBy: none
		sourceColumn: top_pays_sanctions

		annotation SummarizationSetBy = Automatic

	column top_pays_gda
		dataType: string
		lineageTag: 0f00708e-1091-42b8-a047-7d19af272163
		summarizeBy: none
		sourceColumn: top_pays_gda

		annotation SummarizationSetBy = Automatic

	column top_pays_gafi
		dataType: string
		lineageTag: a70a0ee2-c3a7-4430-b601-39e1b39caeff
		summarizeBy: none
		sourceColumn: top_pays_gafi

		annotation SummarizationSetBy = Automatic

	column top_pays_etnc
		dataType: string
		lineageTag: 9d3dc03f-93c1-434d-840c-94d7096f8c83
		summarizeBy: none
		sourceColumn: top_pays_etnc

		annotation SummarizationSetBy = Automatic

	column top_pays_pthr
		dataType: string
		lineageTag: 29ad86b3-d8a8-4d1a-b5f7-6fb69916826c
		summarizeBy: none
		sourceColumn: top_pays_pthr

		annotation SummarizationSetBy = Automatic

	column cd_ficp
		dataType: string
		lineageTag: dce6e49d-a5be-4ece-8193-2c1a77e685cd
		summarizeBy: none
		sourceColumn: cd_ficp

		annotation SummarizationSetBy = Automatic

	column nb_incidents_ficp
		dataType: string
		lineageTag: aa4730ee-2e93-456a-b127-c5d623322bef
		summarizeBy: none
		sourceColumn: nb_incidents_ficp

		annotation SummarizationSetBy = Automatic

	column mnt_pat_biens_immos
		dataType: string
		lineageTag: 72385f4b-56cc-403c-bb0e-ae42b48a4132
		summarizeBy: none
		sourceColumn: mnt_pat_biens_immos

		annotation SummarizationSetBy = Automatic

	column mnt_credits_externes
		dataType: string
		lineageTag: 70081d62-cc1a-4c71-b3ae-d55e1afb3c8e
		summarizeBy: none
		sourceColumn: mnt_credits_externes

		annotation SummarizationSetBy = Automatic

	column mnt_equip_emp
		dataType: string
		lineageTag: 859a7497-4f85-4b78-9646-a37b68ec25c4
		summarizeBy: none
		sourceColumn: mnt_equip_emp

		annotation SummarizationSetBy = Automatic

	column nb_equip_emp
		dataType: string
		lineageTag: 15049f9e-5e3c-478e-9dd7-d82979a8ba93
		summarizeBy: none
		sourceColumn: nb_equip_emp

		annotation SummarizationSetBy = Automatic

	column mnt_equip_tit
		dataType: string
		lineageTag: d5c19060-b957-4b49-b3d3-6bd5b419f38e
		summarizeBy: none
		sourceColumn: mnt_equip_tit

		annotation SummarizationSetBy = Automatic

	column nb_equip_tit
		dataType: string
		lineageTag: c30430ad-9f45-4e4a-bfe7-1265ce3d6bb1
		summarizeBy: none
		sourceColumn: nb_equip_tit

		annotation SummarizationSetBy = Automatic

	column mnt_equip_cau
		dataType: string
		lineageTag: 47cc838e-aaac-4c25-84a3-3c47a6eb8d1d
		summarizeBy: none
		sourceColumn: mnt_equip_cau

		annotation SummarizationSetBy = Automatic

	column mnt_equip_coe
		dataType: string
		lineageTag: 2fd5f3d2-72cb-4eb0-8a14-ef28fdbe912c
		summarizeBy: none
		sourceColumn: mnt_equip_coe

		annotation SummarizationSetBy = Automatic

	column list_fam_pdt
		dataType: string
		lineageTag: 86c179e6-c0d9-4fac-bb42-9800e7817bc7
		summarizeBy: none
		sourceColumn: list_fam_pdt

		annotation SummarizationSetBy = Automatic

	column list_pdt
		dataType: string
		lineageTag: bde8fc23-b348-490b-9155-68e8ca7b1db9
		summarizeBy: none
		sourceColumn: list_pdt

		annotation SummarizationSetBy = Automatic

	column annee_mois_part
		dataType: string
		lineageTag: e6ac0599-6bcd-43f1-8ca6-81d6d9e88166
		summarizeBy: none
		sourceColumn: annee_mois_part

		annotation SummarizationSetBy = Automatic

	partition CLIENT = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("E:\\louvre\\powerbi\\data\\CLIENT.csv"),[Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    #"Promoted" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Typed" = Table.TransformColumnTypes(#"Promoted", {{"id_cli", type text}, {"cli_c_p", type text}, {"nom_cplt", type text}, {"lib_cd_typ", type text}, {"lib_gr", type text}, {"agc_topz", type text}, {"lib_ptf", type text}, {"nom_cons", type text}, {"pay_res", type text}, {"lib_pay_res", type text}, {"couleur_pays", type text}, {"lib_cd_risque_pers", type text}, {"cd_risque_pers", type text}, {"etat_acc", type text}, {"top_client_actif", type text}, {"typ_enrol", type text}, {"gelule_global", Int64.Type}, {"nb_dev_enrol", Int64.Type}, {"age_cli", Int64.Type}, {"dt_enrol", type date}, {"dt_der_cnx", type date}, {"dt_fonc", type date}, {"aum_tit", type number}, {"aum_cot", type number}, {"mnt_pat_epargne", type number}, {"mnt_rev_princ", type number}}, "en-US")
				in
				    #"Typed"

