table EPARGNE
	lineageTag: 90f18229-32f2-4012-b97a-a6ef3595948b

	column id_cli
		dataType: string
		lineageTag: 47391906-7f60-42e7-b1a7-f65cc655ece4
		summarizeBy: none
		sourceColumn: id_cli

		annotation SummarizationSetBy = Automatic

	column num_cnt
		dataType: string
		lineageTag: b54138ed-691f-4800-b6c6-3bcc27b16bb7
		summarizeBy: none
		sourceColumn: num_cnt

		annotation SummarizationSetBy = Automatic

	column perimetre
		dataType: string
		lineageTag: 9759fa7f-fa73-4093-8b4a-2904103f7ab4
		summarizeBy: none
		sourceColumn: perimetre

		annotation SummarizationSetBy = Automatic

	column fam_pdt
		dataType: string
		lineageTag: e20e175b-6dcf-49b3-9879-0e58e071ea4b
		summarizeBy: none
		sourceColumn: fam_pdt

		annotation SummarizationSetBy = Automatic

	column lib_fds
		dataType: string
		lineageTag: ff9c1074-c132-457d-88c7-71f856e27f4f
		summarizeBy: none
		sourceColumn: lib_fds

		annotation SummarizationSetBy = Automatic

	column isin_fds
		dataType: string
		lineageTag: 369932ea-4d3f-4c7e-a349-aa411afa17e9
		summarizeBy: none
		sourceColumn: isin_fds

		annotation SummarizationSetBy = Automatic

	column lib_mod_gest
		dataType: string
		lineageTag: 3ef0334d-2c94-41b2-9a6d-96399c0ee70f
		summarizeBy: none
		sourceColumn: lib_mod_gest

		annotation SummarizationSetBy = Automatic

	column enc_cnt_m
		dataType: double
		lineageTag: 69a4d9f6-70ce-4f89-817a-6e2cce6be9c9
		summarizeBy: sum
		sourceColumn: enc_cnt_m

		annotation SummarizationSetBy = Automatic

	column enc_cnt_n1
		dataType: double
		lineageTag: 58eb3731-94ba-45bc-b62a-f40d77f2a49f
		summarizeBy: sum
		sourceColumn: enc_cnt_n1

		annotation SummarizationSetBy = Automatic

	column col_brute
		dataType: double
		lineageTag: e4e64f26-1115-4774-8193-4e7f53c78496
		summarizeBy: sum
		sourceColumn: col_brute

		annotation SummarizationSetBy = Automatic

	column decollecte
		dataType: double
		lineageTag: 2bd80a0a-0621-4aea-a897-4806bb667c05
		summarizeBy: sum
		sourceColumn: decollecte

		annotation SummarizationSetBy = Automatic

	column col_nette
		dataType: double
		lineageTag: c4c911da-6766-4bf9-9162-b9d502bad8f1
		summarizeBy: sum
		sourceColumn: col_nette

		annotation SummarizationSetBy = Automatic

	column enc_fds_m
		dataType: double
		lineageTag: 3fd8ab0e-5d82-4067-808c-56bfeb6bcc62
		summarizeBy: sum
		sourceColumn: enc_fds_m

		annotation SummarizationSetBy = Automatic

	column stt_cli
		dataType: string
		lineageTag: edd1a1a3-7623-4043-9870-3c8494d95902
		summarizeBy: none
		sourceColumn: stt_cli

		annotation SummarizationSetBy = Automatic

	column lib_ctl
		dataType: string
		lineageTag: fb4da5a0-0860-46e2-ab77-00d46175027b
		summarizeBy: none
		sourceColumn: lib_ctl

		annotation SummarizationSetBy = Automatic

	column lib_fam_niv3_pdt
		dataType: string
		lineageTag: e7bac87d-cd58-48dd-9f09-8c0931b1ee17
		summarizeBy: none
		sourceColumn: lib_fam_niv3_pdt

		annotation SummarizationSetBy = Automatic

	column stt_cnt
		dataType: string
		lineageTag: 1707fa2f-a002-4b68-a05d-1bc945441964
		summarizeBy: none
		sourceColumn: stt_cnt

		annotation SummarizationSetBy = Automatic

	column lib_stt_cnt
		dataType: string
		lineageTag: ea990992-da03-494a-a407-004b93773981
		summarizeBy: none
		sourceColumn: lib_stt_cnt

		annotation SummarizationSetBy = Automatic

	column dt_eff
		dataType: string
		lineageTag: ce7e6c13-23aa-42d2-ad37-dfffa9a3a03c
		summarizeBy: none
		sourceColumn: dt_eff

		annotation SummarizationSetBy = Automatic

	column dt_fin_eff
		dataType: string
		lineageTag: 0609ed80-f3a3-43dc-a7ae-feca8d1b2556
		summarizeBy: none
		sourceColumn: dt_fin_eff

		annotation SummarizationSetBy = Automatic

	column mod_gest
		dataType: string
		lineageTag: 8e00b39f-00bc-45e2-ac89-e769e5c70354
		summarizeBy: none
		sourceColumn: mod_gest

		annotation SummarizationSetBy = Automatic

	column cd_ges
		dataType: string
		lineageTag: cafbdc23-eebb-42ad-8ecf-dfa8803c32e3
		summarizeBy: none
		sourceColumn: cd_ges

		annotation SummarizationSetBy = Automatic

	column lib_cd_ges
		dataType: string
		lineageTag: 2d7ec8ca-d7f6-47a5-84f1-9baa6bc15a94
		summarizeBy: none
		sourceColumn: lib_cd_ges

		annotation SummarizationSetBy = Automatic

	column enc_moy_m
		dataType: string
		lineageTag: 895b1dbb-a488-43cc-93ce-3f5ed25c02af
		summarizeBy: none
		sourceColumn: enc_moy_m

		annotation SummarizationSetBy = Automatic

	column enc_cnt_m1
		dataType: string
		lineageTag: 25d51d99-9d78-4b89-94e5-b3cfcdbf9182
		summarizeBy: none
		sourceColumn: enc_cnt_m1

		annotation SummarizationSetBy = Automatic

	column var_enc
		dataType: string
		lineageTag: 4dde9c02-fd55-43ac-b58a-def9f5823904
		summarizeBy: none
		sourceColumn: var_enc

		annotation SummarizationSetBy = Automatic

	column qte_fds
		dataType: string
		lineageTag: 85108dab-3476-451a-b454-2def35dec897
		summarizeBy: none
		sourceColumn: qte_fds

		annotation SummarizationSetBy = Automatic

	column volatilite_isin
		dataType: string
		lineageTag: 18bcc03b-c328-4440-ae11-1391ea6b36c8
		summarizeBy: none
		sourceColumn: volatilite_isin

		annotation SummarizationSetBy = Automatic

	column isin_risq
		dataType: string
		lineageTag: 8146e14a-87c8-4920-a7fb-ceaf740b03e6
		summarizeBy: none
		sourceColumn: isin_risq

		annotation SummarizationSetBy = Automatic

	column prof_risq
		dataType: string
		lineageTag: 3e74d3dc-0e89-4382-b38c-45eaaca91c94
		summarizeBy: none
		sourceColumn: prof_risq

		annotation SummarizationSetBy = Automatic

	column lib_prof_risq
		dataType: string
		lineageTag: d7417a70-a401-4471-ad33-597d27750d96
		summarizeBy: none
		sourceColumn: lib_prof_risq

		annotation SummarizationSetBy = Automatic

	column prof_exp
		dataType: string
		lineageTag: 73bd7f6c-baf9-496b-8e7f-7cc3882f79a4
		summarizeBy: none
		sourceColumn: prof_exp

		annotation SummarizationSetBy = Automatic

	column lib_prof_exp
		dataType: string
		lineageTag: ccb2bb70-5885-4ec5-8e3d-1d247222d1c2
		summarizeBy: none
		sourceColumn: lib_prof_exp

		annotation SummarizationSetBy = Automatic

	column prof_sfdr
		dataType: string
		lineageTag: 59147360-01e7-4423-bacf-eecb275fce4e
		summarizeBy: none
		sourceColumn: prof_sfdr

		annotation SummarizationSetBy = Automatic

	column mnt_tar_brt
		dataType: string
		lineageTag: 0cc47710-6a00-479c-b0dc-d3f5f50243c2
		summarizeBy: none
		sourceColumn: mnt_tar_brt

		annotation SummarizationSetBy = Automatic

	column mnt_pdt_tar
		dataType: string
		lineageTag: b6bcd5b7-0294-45e8-a6c4-8cca1954c7eb
		summarizeBy: none
		sourceColumn: mnt_pdt_tar

		annotation SummarizationSetBy = Automatic

	column mnt_fdg
		dataType: string
		lineageTag: e138517d-82f7-4003-880d-916a8d3181bc
		summarizeBy: none
		sourceColumn: mnt_fdg

		annotation SummarizationSetBy = Automatic

	column mnt_ddg
		dataType: string
		lineageTag: eb70c200-acef-4ba8-b02b-9b656b802d05
		summarizeBy: none
		sourceColumn: mnt_ddg

		annotation SummarizationSetBy = Automatic

	column tx_int
		dataType: string
		lineageTag: cba70cc6-01ab-4e70-b495-7f61323e67a2
		summarizeBy: none
		sourceColumn: tx_int

		annotation SummarizationSetBy = Automatic

	column cd_bck_ifrs9
		dataType: string
		lineageTag: 23c259e6-f83f-4460-8787-5005c140e6ec
		summarizeBy: none
		sourceColumn: cd_bck_ifrs9

		annotation SummarizationSetBy = Automatic

	column cd_risque
		dataType: string
		lineageTag: 1a0046d8-50e3-4859-a5b0-5debd21dcb30
		summarizeBy: none
		sourceColumn: cd_risque

		annotation SummarizationSetBy = Automatic

	column cd_etat_creance
		dataType: string
		lineageTag: 119bb167-0e9a-4163-b117-8d88a1daf575
		summarizeBy: none
		sourceColumn: cd_etat_creance

		annotation SummarizationSetBy = Automatic

	column mnt_prov_b_ifrs9
		dataType: string
		lineageTag: c8f6fe3d-ce95-4e7f-9efb-c2ca096000dd
		summarizeBy: none
		sourceColumn: mnt_prov_b_ifrs9

		annotation SummarizationSetBy = Automatic

	column mnt_prov_hb_ifrs9
		dataType: string
		lineageTag: fe7733e2-a3cf-4171-ad75-5810f2938787
		summarizeBy: none
		sourceColumn: mnt_prov_hb_ifrs9

		annotation SummarizationSetBy = Automatic

	column mnt_dot
		dataType: string
		lineageTag: 931cff80-d0af-4f7e-b783-f4b4524b6929
		summarizeBy: none
		sourceColumn: mnt_dot

		annotation SummarizationSetBy = Automatic

	column mnt_rep
		dataType: string
		lineageTag: e7378da7-18f1-4119-a0b2-40cf952da990
		summarizeBy: none
		sourceColumn: mnt_rep

		annotation SummarizationSetBy = Automatic

	column mnt_psp
		dataType: string
		lineageTag: 0911ea6e-88a4-424f-977a-003ceeedc559
		summarizeBy: none
		sourceColumn: mnt_psp

		annotation SummarizationSetBy = Automatic

	column total_rwa
		dataType: string
		lineageTag: b404629a-e56a-429b-9bb3-5aa96e42f553
		summarizeBy: none
		sourceColumn: total_rwa

		annotation SummarizationSetBy = Automatic

	column top_nanti
		dataType: string
		lineageTag: fba9490a-8a0f-4e2e-a62c-e68b9be79022
		summarizeBy: none
		sourceColumn: top_nanti

		annotation SummarizationSetBy = Automatic

	column mnt_nanti
		dataType: string
		lineageTag: 24f8d987-d81a-4847-af01-74eb4f80e639
		summarizeBy: none
		sourceColumn: mnt_nanti

		annotation SummarizationSetBy = Automatic

	column assur
		dataType: string
		lineageTag: c118a4b4-2273-4c92-9eaa-223c3f7c4581
		summarizeBy: none
		sourceColumn: assur

		annotation SummarizationSetBy = Automatic

	column Lib_Bucket_IFRS9
		dataType: string
		lineageTag: 4d583fc7-b4d6-43ba-95e6-a742a9b94669
		summarizeBy: none
		sourceColumn: Lib_Bucket_IFRS9

		annotation SummarizationSetBy = Automatic

	column annee_mois_part
		dataType: string
		lineageTag: 2732973c-34db-4c6f-8099-cf6d72e8cb68
		summarizeBy: none
		sourceColumn: annee_mois_part

		annotation SummarizationSetBy = Automatic

	partition EPARGNE = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("E:\\louvre\\powerbi\\data\\EPARGNE.csv"),[Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    #"Promoted" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Typed" = Table.TransformColumnTypes(#"Promoted", {{"id_cli", type text}, {"num_cnt", type text}, {"perimetre", type text}, {"fam_pdt", type text}, {"lib_fds", type text}, {"isin_fds", type text}, {"lib_mod_gest", type text}, {"enc_cnt_m", type number}, {"enc_cnt_n1", type number}, {"col_brute", type number}, {"decollecte", type number}, {"col_nette", type number}, {"enc_fds_m", type number}}, "en-US")
				in
				    #"Typed"

