table TRANSACTION
	lineageTag: 353dd79d-f50d-420b-b0e6-8ff664a5140c

	column id_cli
		dataType: string
		lineageTag: 1163e412-d184-4459-b631-4ca3e421caba
		summarizeBy: none
		sourceColumn: id_cli

		annotation SummarizationSetBy = Automatic

	column num_cnt
		dataType: string
		lineageTag: e397618b-0b02-4059-a227-49c203cdaa12
		summarizeBy: none
		sourceColumn: num_cnt

		annotation SummarizationSetBy = Automatic

	column perimetre
		dataType: string
		lineageTag: 2b8b1342-37d7-47a4-9159-46b1ef21d8ec
		summarizeBy: none
		sourceColumn: perimetre

		annotation SummarizationSetBy = Automatic

	column typ_evt_lv1
		dataType: string
		lineageTag: 77ce98e2-0404-4a69-ba2b-3e2521f15f86
		summarizeBy: none
		sourceColumn: typ_evt_lv1

		annotation SummarizationSetBy = Automatic

	column lib_evt_lv1
		dataType: string
		lineageTag: ae4eecda-a77c-4932-939a-c8a8c5fbd3b9
		summarizeBy: none
		sourceColumn: lib_evt_lv1

		annotation SummarizationSetBy = Automatic

	column sens
		dataType: string
		lineageTag: 02450fe9-9e39-4134-888a-57cf3d718cc1
		summarizeBy: none
		sourceColumn: sens

		annotation SummarizationSetBy = Automatic

	column mnt_evt
		dataType: double
		lineageTag: 38636911-5289-4201-96c2-32520f68b186
		summarizeBy: sum
		sourceColumn: mnt_evt

		annotation SummarizationSetBy = Automatic

	column devise_compte
		dataType: string
		lineageTag: d54ef8ec-a442-4c3a-b4d6-79d161f5ae81
		summarizeBy: none
		sourceColumn: devise_compte

		annotation SummarizationSetBy = Automatic

	column mode_paiement
		dataType: string
		lineageTag: 2e8f33ee-28d8-49a4-9683-9e7ec9ca9cda
		summarizeBy: none
		sourceColumn: mode_paiement

		annotation SummarizationSetBy = Automatic

	column canal_ordre
		dataType: string
		lineageTag: c70998dc-1a54-48ce-8a47-6af021a5cdde
		summarizeBy: none
		sourceColumn: canal_ordre

		annotation SummarizationSetBy = Automatic

	column ctrpty_pays
		dataType: string
		lineageTag: 485903c5-66d9-4cca-8296-a70c7b6f6748
		summarizeBy: none
		sourceColumn: ctrpty_pays

		annotation SummarizationSetBy = Automatic

	column ctrpty_couleur_pays
		dataType: string
		lineageTag: def58672-0c25-46d3-ab2d-e0a6aae32e2a
		summarizeBy: none
		sourceColumn: ctrpty_couleur_pays

		annotation SummarizationSetBy = Automatic

	column ind_3ds
		dataType: int64
		lineageTag: 66d30ba8-3d26-4b6a-b28b-cf509665366b
		summarizeBy: sum
		sourceColumn: ind_3ds

		annotation SummarizationSetBy = Automatic

	column Transaction_Sensible
		dataType: int64
		lineageTag: eafeae90-9fa9-4379-811b-cff2fe41a543
		summarizeBy: sum
		sourceColumn: Transaction_Sensible

		annotation SummarizationSetBy = Automatic

	column dt_realisation
		dataType: dateTime
		formatString: Long Date
		lineageTag: 57262b4a-bf83-4bce-aa3b-f88f36bd32c0
		summarizeBy: none
		sourceColumn: dt_realisation

		variation Variation
			isDefault
			relationship: 7746df7f-d180-494d-a4bb-9d7df9253220
			defaultHierarchy: LocalDateTable_e73ad3e1-32f4-42c3-8a6d-bc8280424615.'Hiérarchie de dates'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column typ_evt
		dataType: string
		lineageTag: 0682c700-11c8-4c86-b110-c6d5f5ee7c05
		summarizeBy: none
		sourceColumn: typ_evt

		annotation SummarizationSetBy = Automatic

	column val_evt_lv1
		dataType: string
		lineageTag: efc29182-3485-4fff-a68a-12ec1d5c7f78
		summarizeBy: none
		sourceColumn: val_evt_lv1

		annotation SummarizationSetBy = Automatic

	column typ_evt_lv2
		dataType: string
		lineageTag: 24f72dc1-8e98-4a83-89d4-0a84d6b7f919
		summarizeBy: none
		sourceColumn: typ_evt_lv2

		annotation SummarizationSetBy = Automatic

	column val_evt_lv2
		dataType: string
		lineageTag: 266ab6c3-c24b-4e90-a767-335b17b50510
		summarizeBy: none
		sourceColumn: val_evt_lv2

		annotation SummarizationSetBy = Automatic

	column mnt_devise
		dataType: string
		lineageTag: c800b793-a05c-4436-a1d0-d0660b51c7b8
		summarizeBy: none
		sourceColumn: mnt_devise

		annotation SummarizationSetBy = Automatic

	column devise_operation
		dataType: string
		lineageTag: b09c756a-5940-4516-a209-5d2e6693db7b
		summarizeBy: none
		sourceColumn: devise_operation

		annotation SummarizationSetBy = Automatic

	column dt_demande
		dataType: string
		lineageTag: 610eadf0-a2d6-4ade-98c6-31d719fe0ece
		summarizeBy: none
		sourceColumn: dt_demande

		annotation SummarizationSetBy = Automatic

	column dt_validation
		dataType: string
		lineageTag: f41a892a-15a7-454a-a21c-5858a47182eb
		summarizeBy: none
		sourceColumn: dt_validation

		annotation SummarizationSetBy = Automatic

	column typ_paiement
		dataType: string
		lineageTag: 418a50e3-cff6-4cd9-86b6-1d6c779579d8
		summarizeBy: none
		sourceColumn: typ_paiement

		annotation SummarizationSetBy = Automatic

	column ind_sans_contact
		dataType: string
		lineageTag: 3f53c2ea-c281-4bb8-b6c2-387db96c4bc0
		summarizeBy: none
		sourceColumn: ind_sans_contact

		annotation SummarizationSetBy = Automatic

	column ind_saisie_pin
		dataType: string
		lineageTag: fead2474-109a-487a-b74b-2a498e8ebfe7
		summarizeBy: none
		sourceColumn: ind_saisie_pin

		annotation SummarizationSetBy = Automatic

	column canal_init
		dataType: string
		lineageTag: 3450a0ca-1a17-49db-8729-41a23d3702ca
		summarizeBy: none
		sourceColumn: canal_init

		annotation SummarizationSetBy = Automatic

	column ctrpty_nom
		dataType: string
		lineageTag: fe55180a-42ab-4070-91d8-deedc7268f83
		summarizeBy: none
		sourceColumn: ctrpty_nom

		annotation SummarizationSetBy = Automatic

	column ctrpty_bnq_bic
		dataType: string
		lineageTag: e370cdec-d14f-403e-89df-99124faa6953
		summarizeBy: none
		sourceColumn: ctrpty_bnq_bic

		annotation SummarizationSetBy = Automatic

	column cli_cd_pays_iso
		dataType: string
		lineageTag: 56585968-1e38-4589-a724-a033ded733a2
		summarizeBy: none
		sourceColumn: cli_cd_pays_iso

		annotation SummarizationSetBy = Automatic

	column cli_couleur_pays
		dataType: string
		lineageTag: 124dfabb-27d8-449a-a087-b2e66a57662c
		summarizeBy: none
		sourceColumn: cli_couleur_pays

		annotation SummarizationSetBy = Automatic

	column cli_niveau_risque_pays
		dataType: string
		lineageTag: 73a491ab-d17d-4af6-882f-608fe9013d03
		summarizeBy: none
		sourceColumn: cli_niveau_risque_pays

		annotation SummarizationSetBy = Automatic

	column cli_top_pays_embargo
		dataType: string
		lineageTag: a7aa0986-e80b-479a-9102-955356ec37f0
		summarizeBy: none
		sourceColumn: cli_top_pays_embargo

		annotation SummarizationSetBy = Automatic

	column cli_top_pays_sanctions
		dataType: string
		lineageTag: 5f9819c5-e989-41f1-82b9-39e24bf01ba2
		summarizeBy: none
		sourceColumn: cli_top_pays_sanctions

		annotation SummarizationSetBy = Automatic

	column cli_top_pays_gda
		dataType: string
		lineageTag: 796a465b-626b-4cdd-a8c9-3c5cf427bd1b
		summarizeBy: none
		sourceColumn: cli_top_pays_gda

		annotation SummarizationSetBy = Automatic

	column cli_top_pays_gafi
		dataType: string
		lineageTag: d021ee6c-6cbf-4d37-af8d-2134d1d6aa6a
		summarizeBy: none
		sourceColumn: cli_top_pays_gafi

		annotation SummarizationSetBy = Automatic

	column cli_top_pays_etnc
		dataType: string
		lineageTag: 9fd5da27-354f-4031-94cd-fb9544902797
		summarizeBy: none
		sourceColumn: cli_top_pays_etnc

		annotation SummarizationSetBy = Automatic

	column cli_top_pays_pthr
		dataType: string
		lineageTag: 60ac74f2-feb8-4925-9324-2a0c2edf8573
		summarizeBy: none
		sourceColumn: cli_top_pays_pthr

		annotation SummarizationSetBy = Automatic

	column ctrpty_cd_pays_iso
		dataType: string
		lineageTag: 60fe5481-b7ef-4393-9a1b-0deb3966bd74
		summarizeBy: none
		sourceColumn: ctrpty_cd_pays_iso

		annotation SummarizationSetBy = Automatic

	column ctrpty_niveau_risque_pays
		dataType: string
		lineageTag: c54f751c-7ebb-46e6-9c45-5187285eca39
		summarizeBy: none
		sourceColumn: ctrpty_niveau_risque_pays

		annotation SummarizationSetBy = Automatic

	column ctrpty_top_pays_embargo
		dataType: string
		lineageTag: 6f23593a-0230-433d-9ddb-f2c1791ddb0f
		summarizeBy: none
		sourceColumn: ctrpty_top_pays_embargo

		annotation SummarizationSetBy = Automatic

	column ctrpty_top_pays_sanctions
		dataType: string
		lineageTag: 8419e991-3b72-4497-a93d-5f8fb6fc0887
		summarizeBy: none
		sourceColumn: ctrpty_top_pays_sanctions

		annotation SummarizationSetBy = Automatic

	column ctrpty_top_pays_gda
		dataType: string
		lineageTag: 996c84cc-9d94-4ca2-93c7-eaae94056724
		summarizeBy: none
		sourceColumn: ctrpty_top_pays_gda

		annotation SummarizationSetBy = Automatic

	column ctrpty_top_pays_gafi
		dataType: string
		lineageTag: 5997b83e-82a3-46fb-b684-069e8e0db987
		summarizeBy: none
		sourceColumn: ctrpty_top_pays_gafi

		annotation SummarizationSetBy = Automatic

	column ctrpty_bnq_cd_pays_iso
		dataType: string
		lineageTag: 97c72ac5-c853-45ff-a814-6d454c261ebc
		summarizeBy: none
		sourceColumn: ctrpty_bnq_cd_pays_iso

		annotation SummarizationSetBy = Automatic

	column ctrpty_bnq_couleur_pays
		dataType: string
		lineageTag: c2a944bb-0c8d-4b17-9efb-b22efe9aa99e
		summarizeBy: none
		sourceColumn: ctrpty_bnq_couleur_pays

		annotation SummarizationSetBy = Automatic

	column ctrpty_bnq_top_pays_embargo
		dataType: string
		lineageTag: 3e25d2de-3966-4bef-bf36-0a2ba21d0423
		summarizeBy: none
		sourceColumn: ctrpty_bnq_top_pays_embargo

		annotation SummarizationSetBy = Automatic

	column ctrpty_bnq_top_pays_sanctions
		dataType: string
		lineageTag: 4c96a667-634a-4aa9-93ce-0534be03a74f
		summarizeBy: none
		sourceColumn: ctrpty_bnq_top_pays_sanctions

		annotation SummarizationSetBy = Automatic

	column annee_mois_part
		dataType: string
		lineageTag: 37f33b52-92cb-490d-8a68-6672c92d49d5
		summarizeBy: none
		sourceColumn: annee_mois_part

		annotation SummarizationSetBy = Automatic

	partition TRANSACTION = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("E:\\louvre\\powerbi\\data\\TRANSACTION.csv"),[Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    #"Promoted" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Typed" = Table.TransformColumnTypes(#"Promoted", {{"id_cli", type text}, {"num_cnt", type text}, {"perimetre", type text}, {"typ_evt_lv1", type text}, {"lib_evt_lv1", type text}, {"sens", type text}, {"mnt_evt", type number}, {"devise_compte", type text}, {"mode_paiement", type text}, {"canal_ordre", type text}, {"ctrpty_pays", type text}, {"ctrpty_couleur_pays", type text}, {"ind_3ds", Int64.Type}, {"Transaction_Sensible", Int64.Type}, {"dt_realisation", type date}}, "en-US")
				in
				    #"Typed"

